version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        curl -L -o cirrus https://github.com/cirruslabs/cirrus-cli/releases/latest/download/cirrus-linux-amd64
        sudo mv cirrus /usr/local/bin/cirrus
        sudo chmod +x /usr/local/bin/cirrus
        git config --global user.name galang8664
        git config --global user.email ardimasgalang5@gmail.com
        git config --global color.ui false
        PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
        repo init --depth=1 --no-repo-verify -u https://github.com/Evolution-X/manifest -b tiramisu -g default,-mips,-darwin,-notdefault
        git clone https://github.com/galang8664/local_manifest.git --depth 1 -b evox .repo/local_manifests
        repo sync
        source build/envsetup.sh
        lunch evolution_lava-userdebug
        mka evolution
        
     - run: cirrus run
