version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        curl -L -o cirrus https://github.com/cirruslabs/cirrus-cli/releases/latest/download/cirrus-linux-amd64
        sudo mv cirrus /usr/local/bin/cirrus
        sudo chmod +x /usr/local/bin/cirrus
        git config --global user.name galang8664
        git config --global user.email ardimasgalang5@gmail.com
        git config --global color.ui false
        PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
        git clone https://github.com/galang8664/builder.git --depth 1 -b lava-RiceDroid-thirteen-galang8664
        cd builder
        bash .cirrus.yml
        
     - run: cirrus run
