version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        curl -L -o cirrus https://github.com/cirruslabs/cirrus-cli/releases/latest/download/cirrus-linux-amd64
        sudo mv cirrus /usr/local/bin/cirrus
        sudo chmod +x /usr/local/bin/cirrus
        cd 
        git clone https://github.com/AndroidDumps/dumpyara
        cd dumpyara
        wget https://bigota.d.miui.com/V13.0.2.0.SJCMIXM/miui_LANCELOTGlobal_V13.0.2.0.SJCMIXM_dd107c921b_12.0.zip
        wget https://neomirror.neomirror.workers.dev/0:/lineage-20.0-20221203-UNOFFICIAL-lancelot.zip
        bash setup.sh
        bash dumpyara.sh ./miui_LANCELOTGlobal_V13.0.2.0.SJCMIXM_dd107c921b_12.0.zip
        

     - run: cirrus run
